import 'dart:io';

final class HomeEntryBackRule {
  const HomeEntryBackRule({
    required this.id,
    required this.area,
    required this.file,
    required this.requiredSnippets,
    required this.notes,
    this.forbiddenSnippets = const [],
  });

  final String id;
  final String area;
  final String file;
  final List<String> requiredSnippets;
  final List<String> forbiddenSnippets;
  final String notes;
}

final class HomeEntryBackFinding {
  const HomeEntryBackFinding({
    required this.rule,
    required this.fileExists,
    required this.missingRequired,
    required this.presentForbidden,
    required this.line,
  });

  final HomeEntryBackRule rule;
  final bool fileExists;
  final List<String> missingRequired;
  final List<String> presentForbidden;
  final int line;

  bool get passed =>
      fileExists && missingRequired.isEmpty && presentForbidden.isEmpty;

  String get status => passed ? 'PASS' : 'FAIL';

  String get evidence {
    if (!fileExists) return 'missing file';
    if (missingRequired.isNotEmpty) {
      return 'missing: ${missingRequired.join(' | ')}';
    }
    if (presentForbidden.isNotEmpty) {
      return 'forbidden: ${presentForbidden.join(' | ')}';
    }
    return line > 0 ? 'line $line' : 'present';
  }
}

void main(List<String> args) {
  final checkOnly = args.contains('--check');
  final appRoot = _findAppRoot();
  final repoRoot = appRoot.uri.resolve('..').toFilePath();
  final docsDir = Directory('${repoRoot}docs/02_FLUTTER_MIGRATION');
  final markdownFile = File(
    '${docsDir.path}/audits/VitTrade-Home-Entry-Back-Navigation-Audit.md',
  );
  final csvFile = File(
    '${docsDir.path}/audits/VitTrade-Home-Entry-Back-Navigation-Audit.csv',
  );

  final findings = _rules.map((rule) => _evaluate(rule, appRoot)).toList();
  final markdown = _renderMarkdown(findings);
  final csv = _renderCsv(findings);
  final summary = _renderSummary(findings);

  if (checkOnly) {
    final failures = <String>[];
    if (!markdownFile.existsSync()) {
      failures.add('Home entry back navigation markdown artifact is missing.');
    } else if (markdownFile.readAsStringSync() != markdown) {
      failures.add('Home entry back navigation markdown artifact is stale.');
    }

    if (!csvFile.existsSync()) {
      failures.add('Home entry back navigation CSV artifact is missing.');
    } else if (csvFile.readAsStringSync() != csv) {
      failures.add('Home entry back navigation CSV artifact is stale.');
    }

    final failedRules = findings.where((finding) => !finding.passed).toList();
    if (failedRules.isNotEmpty) {
      failures.add(
        'Home entry back navigation audit found '
        '${failedRules.length} failing rule(s).',
      );
    }

    if (failures.isNotEmpty) {
      for (final failure in failures) {
        stderr.writeln(failure);
      }
      stderr.writeln(
        'Run `dart run tool/home_entry_back_navigation_audit.dart` '
        'from flutter_app/.',
      );
      exitCode = 1;
      return;
    }

    stdout.write(summary);
    stdout.writeln('Home entry back navigation artifacts are current.');
    return;
  }

  docsDir.createSync(recursive: true);
  markdownFile.writeAsStringSync(markdown);
  csvFile.writeAsStringSync(csv);
  stdout.writeln('Wrote ${markdownFile.path}');
  stdout.writeln('Wrote ${csvFile.path}');
  stdout.write(summary);
}

HomeEntryBackFinding _evaluate(HomeEntryBackRule rule, Directory appRoot) {
  final file = File('${appRoot.path}/${rule.file}');
  if (!file.existsSync()) {
    return HomeEntryBackFinding(
      rule: rule,
      fileExists: false,
      missingRequired: rule.requiredSnippets,
      presentForbidden: const [],
      line: 0,
    );
  }

  final source = file.readAsStringSync();
  final missingRequired = [
    for (final snippet in rule.requiredSnippets)
      if (!source.contains(snippet)) snippet,
  ];
  final presentForbidden = [
    for (final snippet in rule.forbiddenSnippets)
      if (source.contains(snippet)) snippet,
  ];
  final line = _firstSnippetLine(source, rule.requiredSnippets);

  return HomeEntryBackFinding(
    rule: rule,
    fileExists: true,
    missingRequired: missingRequired,
    presentForbidden: presentForbidden,
    line: line,
  );
}

String _renderMarkdown(List<HomeEntryBackFinding> findings) {
  final buffer = StringBuffer()
    ..writeln('# VitTrade Home Entry Back Navigation Audit')
    ..writeln()
    ..writeln(
      'Generated by `dart run tool/home_entry_back_navigation_audit.dart`.',
    )
    ..writeln()
    ..writeln(_renderSummary(findings).trimRight())
    ..writeln()
    ..writeln('| ID | Area | File | Status | Evidence | Notes |')
    ..writeln('| --- | --- | --- | --- | --- | --- |');

  for (final finding in findings) {
    buffer.writeln(
      '| ${finding.rule.id} '
      '| ${finding.rule.area} '
      '| `${finding.rule.file}` '
      '| ${finding.status} '
      '| ${_escapeTable(finding.evidence)} '
      '| ${_escapeTable(finding.rule.notes)} |',
    );
  }

  return buffer.toString();
}

String _renderCsv(List<HomeEntryBackFinding> findings) {
  final rows = [
    ['id', 'area', 'file', 'status', 'evidence', 'notes'],
    for (final finding in findings)
      [
        finding.rule.id,
        finding.rule.area,
        finding.rule.file,
        finding.status,
        finding.evidence,
        finding.rule.notes,
      ],
  ];

  return '${rows.map((row) => row.map(_escapeCsv).join(',')).join('\n')}\n';
}

String _renderSummary(List<HomeEntryBackFinding> findings) {
  final passed = findings.where((finding) => finding.passed).length;
  final failed = findings.length - passed;
  return 'home_entry_back_rules=${findings.length}\n'
      'passed=$passed\n'
      'failed=$failed\n';
}

Directory _findAppRoot() {
  final current = Directory.current;
  if (Directory('${current.path}/lib/app/router/route_groups').existsSync()) {
    return current;
  }

  final nested = Directory('${current.path}/flutter_app');
  if (Directory('${nested.path}/lib/app/router/route_groups').existsSync()) {
    return nested;
  }

  throw StateError('Run from repo root or flutter_app/.');
}

int _firstSnippetLine(String source, List<String> snippets) {
  for (final snippet in snippets) {
    final index = source.indexOf(snippet);
    if (index < 0) continue;
    return '\n'.allMatches(source.substring(0, index)).length + 1;
  }
  return 0;
}

String _escapeTable(String value) {
  return value.replaceAll('|', r'\|').replaceAll('\n', '<br>');
}

String _escapeCsv(String value) {
  final escaped = value.replaceAll('"', '""');
  return '"$escaped"';
}

const _rules = [..._homeMatrixSourceRules, ..._homeEntryContractRules];

const _homeMatrixSourceRules = [
  HomeEntryBackRule(
    id: 'HEB-001',
    area: 'Matrix source',
    file: 'lib/features/home/presentation/widgets/phone/home_header.dart',
    requiredSnippets: ["onNavigate('/search')"],
    notes: 'Header Search source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-002',
    area: 'Matrix source',
    file: 'lib/features/home/presentation/widgets/phone/home_header.dart',
    requiredSnippets: ["onNavigate('/notifications')"],
    notes: 'Header Notifications source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-003',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["routePath: '/wallet/withdraw/USDT'"],
    notes: 'Next-action withdraw source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-004',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["id: 'spot-btc'", "routePath: '/trade/btcusdt'"],
    notes: 'Recent BTC/USDT source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-005',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["id: 'p2p-usdt'", "routePath: '/p2p'"],
    notes: 'Recent P2P source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-006',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["id: 'copy-alpha'", "routePath: '/trade/copy-trading'"],
    notes: 'Recent Copy Trade source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-030',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["routePath: '/earn'"],
    notes: 'Earn/Staking Home entry source is present (canonical /earn).',
  ),
  HomeEntryBackRule(
    id: 'HEB-007',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["label: 'Mua nhanh'", "routePath: '/trade/btcusdt'"],
    notes: 'Quick action Mua nhanh source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-008',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["label: 'Chuyển đổi'", "routePath: '/trade/convert'"],
    notes: 'Quick action Chuyển đổi (Convert) source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-009',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["label: 'Margin'", "routePath: '/trade/margin'"],
    notes: 'Quick action Margin source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-010',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["label: 'Bot'", "routePath: '/trade/bots'"],
    notes: 'Quick action Bot source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-011',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: [
      "label: 'Copy Trade'",
      "routePath: '/trade/copy-trading'",
    ],
    notes: 'Quick action Copy Trade source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-012',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["routePath: '/dca'"],
    notes: 'Quick action DCA source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-013',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["routePath: '/wallet'"],
    notes: 'Quick action Wallet source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-014',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["label: 'P2P'", "routePath: '/p2p'"],
    notes: 'Quick action P2P source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-015',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["label: 'Staking'", "routePath: '/earn'"],
    notes: 'Quick action Staking → /earn source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-016',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["routePath: '/earn/savings'"],
    notes: 'Quick action Savings source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-017',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["label: 'Launchpad'", "routePath: '/launchpad'"],
    notes: 'Quick action Launchpad source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-018',
    area: 'Matrix source',
    file: 'lib/features/home/presentation/pages/phone/home_page_sections.dart',
    requiredSnippets: ["onTap: () => onNavigate('/markets/predictions')"],
    notes: 'Discovery Predictions entry (not Home quick action) is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-019',
    area: 'Matrix source',
    file: 'lib/features/home/presentation/pages/phone/home_page_sections.dart',
    requiredSnippets: ["onTap: () => onNavigate('/arena')"],
    notes: 'Discovery Arena entry (not Home quick action) is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-020',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["routePath: '/rewards'"],
    notes: 'Quick action Rewards source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-021',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: [
      'Không gồm Support / Referral / Discovery (Predictions, Arena).',
    ],
    notes: 'Support removed from Home quick actions (Profile menu only).',
  ),
  HomeEntryBackRule(
    id: 'HEB-022',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: ["routePath: '/topics'"],
    notes: 'Quick action Topics source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-023',
    area: 'Matrix source',
    file: 'lib/features/home/data/home_mock_data.dart',
    requiredSnippets: [
      'Không gồm Support / Referral / Discovery (Predictions, Arena).',
    ],
    notes: 'Referral removed from Home quick actions (Profile menu only).',
  ),
  HomeEntryBackRule(
    id: 'HEB-024',
    area: 'Matrix source',
    file: 'lib/features/home/presentation/pages/phone/home_page_sections.dart',
    requiredSnippets: ["onTap: () => onNavigate('/markets/predictions')"],
    notes: 'Discovery Prediction Markets source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-025',
    area: 'Matrix source',
    file: 'lib/features/home/presentation/pages/phone/home_page_sections.dart',
    requiredSnippets: ["onTap: () => onNavigate('/arena')"],
    notes: 'Discovery Open Arena source is present.',
  ),
  HomeEntryBackRule(
    id: 'HEB-026',
    area: 'Matrix source',
    file: 'lib/features/home/presentation/pages/phone/home_page_sections.dart',
    requiredSnippets: ["onNavigate('/markets')"],
    notes: 'Markets root source is present; system back uses Home history.',
  ),
  HomeEntryBackRule(
    id: 'HEB-027',
    area: 'Matrix source',
    file: 'lib/features/home/presentation/pages/phone/home_page_sections.dart',
    requiredSnippets: [
      'class _MarketSection',
      "onNavigate('/pair/\${pairs[i].id}')",
    ],
    notes: 'Market section pair source is present.',
  ),
];

const _homeEntryContractRules = [
  HomeEntryBackRule(
    id: 'HEB-C01',
    area: 'Home outbound',
    file: 'lib/features/home/presentation/pages/phone/home_page_state.dart',
    // GĐ4-F6: lint unawaited_futures bọc push thành
    // `unawaited(context.push(path));` — matcher nhận cả 2 dạng cũ/mới
    // (bài học audit-tool-text-matchers: đổi call site phải grep tool/).
    requiredSnippets: ['context.push(path)'],
    forbiddenSnippets: ['context.go(path);'],
    notes: 'Home feature/product entries preserve route history.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02A',
    area: 'Trade pair entry',
    file: 'lib/features/trade/presentation/pages/phone/trade_page_state.dart',
    requiredSnippets: [
      'widget.chartVariant == TradeChartVariant.pairRoute || context.canPop()',
      'fallbackPath: AppRoutePaths.trade',
      'mode: BackNavigationMode.historyThenFallback',
    ],
    notes:
        'Home opens /trade/:pair with Home history; direct entry falls back to Trade.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02B',
    area: 'Convert entry',
    file: 'lib/features/trade/presentation/pages/convert/convert_page.dart',
    requiredSnippets: [
      'fallbackPath: AppRoutePaths.trade',
      'mode: BackNavigationMode.historyThenFallback',
    ],
    notes:
        'Convert pops to Home when Home-pushed and falls back to Trade directly.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02C',
    area: 'Margin entry',
    file:
        'lib/features/trade/presentation/pages/margin/margin_trading_page.dart',
    requiredSnippets: [
      'fallbackPath: AppRoutePaths.trade',
      'mode: BackNavigationMode.historyThenFallback',
    ],
    notes: 'Margin keeps Trade as direct parent fallback.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02D',
    area: 'Bot entry',
    file:
        'lib/features/trade_bots/presentation/pages/hub/trading_bots_page.dart',
    requiredSnippets: [
      'fallbackPath: AppRoutePaths.trade',
      'mode: BackNavigationMode.historyThenFallback',
    ],
    notes: 'Bot keeps Trade as direct parent fallback.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02E',
    area: 'Copy Trade entry',
    file:
        'lib/features/trade_copy/presentation/pages/hub/copy_trading_page.dart',
    requiredSnippets: [
      'fallbackPath: AppRoutePaths.trade',
      'mode: BackNavigationMode.historyThenFallback',
    ],
    notes: 'Copy Trade keeps Trade as direct parent fallback.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02F',
    area: 'DCA entry',
    file:
        'lib/features/dca/presentation/pages/hub/dca_page_state_overview.dart',
    requiredSnippets: [
      'fallbackPath: AppRoutePaths.trade',
      'mode: BackNavigationMode.historyThenFallback',
    ],
    notes: 'DCA is reached from Home but its safe direct parent remains Trade.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02G',
    area: 'Savings entry',
    file:
        'lib/features/earn_savings/presentation/pages/savings/savings_page.dart',
    requiredSnippets: [
      'fallbackPath: snapshot.backRoute',
      'mode: BackNavigationMode.historyThenFallback',
    ],
    notes:
        'Savings pops to Home when Home-pushed and falls back to Earn directly.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02H',
    area: 'Prediction Markets entry',
    file:
        'lib/features/predictions/presentation/pages/hub/predictions_home_page.dart',
    requiredSnippets: [
      'fallbackPath: AppRoutePaths.markets',
      'mode: BackNavigationMode.historyThenFallback',
    ],
    notes: 'Prediction Markets falls back to Markets when opened directly.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02I',
    area: 'Wallet entry',
    file: 'lib/features/wallet/presentation/pages/phone/wallet_page.dart',
    requiredSnippets: [
      'final showBack = context.canPop();',
      'fallbackPath: AppRoutePaths.home',
      'mode: BackNavigationMode.historyThenFallback',
    ],
    notes: 'Wallet shows a back button only when Home/source history exists.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02J',
    area: 'Withdraw next action',
    file: 'lib/features/wallet/presentation/pages/transfer/withdraw_page.dart',
    requiredSnippets: [
      'fallbackPath: AppRoutePaths.wallet',
      'mode: BackNavigationMode.historyThenFallback',
    ],
    notes:
        'Home next-action withdraw returns Home; direct withdraw falls back to Wallet.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02K',
    area: 'Pair detail entry',
    file: 'lib/features/markets/presentation/pages/pair/pair_detail_page.dart',
    requiredSnippets: [
      'fallbackPath: AppRoutePaths.markets',
      'mode: BackNavigationMode.historyThenFallback',
    ],
    notes:
        'Home market rows return Home; direct pair detail falls back to Markets.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C02L',
    area: 'Instrument chrome',
    file: 'lib/shared/layout/vit_top_chrome.dart',
    requiredSnippets: ['if (showBack) ...[', 'if (leading != null) ...['],
    notes:
        'Instrument headers can show both back and an instrument leading slot.',
  ),
  HomeEntryBackRule(
    id: 'HEB-C03',
    area: 'Home source coverage',
    file: 'lib/features/home/presentation/pages/phone/home_page_common.dart',
    requiredSnippets: ["part of 'home_page.dart';"],
    forbiddenSnippets: ['onNavigate('],
    notes:
        'Part 03 currently has no Home outgoing route; update matrix if this changes.',
  ),
];
