// Tablet Spacing & Gutter Standard — audit scanner.
//
// Locks the static half of
// docs/02_FLUTTER_MIGRATION/standards/Tablet-Spacing-Gutter-Standard.md
// across every tablet-surface Dart file under lib/ (path contains
// "/tablet/", or the file name mentions "tablet"). The tablet surface is
// already at ZERO literal spacing — these rules are absolute (no baseline,
// no ratchet): any new literal fails CI outright.
//
//   S1 literal gap      — `SizedBox(height|width: <number>` must reference
//                         an AppSpacing (or module spacing) token instead.
//   S2 literal inset    — EdgeInsets constructors with numeric literals
//                         (`EdgeInsets.all(12)`) must use tokens; token
//                         references like `AppSpacing.x5` do not match
//                         because the digit is glued to a word char.
//   S3 literal stroke   — `thickness: <number>` and `Divider(height:
//                         <number>` must use AppSpacing.dividerHairline /
//                         token references.
//
// Usage (from flutter_app/):
//   dart run tool/tablet_spacing_audit.dart            # regen artifact
//   dart run tool/tablet_spacing_audit.dart --check    # CI staleness
import 'dart:io';

const _artifactPath =
    '../docs/02_FLUTTER_MIGRATION/audits/VitTrade-Tablet-Spacing-Audit.csv';

final _literalGapRe = RegExp(r'SizedBox\(\s*(height|width):\s*\d');
final _literalInsetRe = RegExp(
  r'EdgeInsets(?:Directional)?\.\w+\([^)]*\b\d+\.?\d*\b[^)]*\)',
);
final _literalStrokeRe = RegExp(r'thickness:\s*\d');

void main(List<String> args) {
  final checkOnly = args.contains('--check');

  final rows = <SpacingRow>[];
  final libDir = Directory('lib');
  if (!libDir.existsSync()) {
    stderr.writeln('Run from flutter_app/ — lib/ not found.');
    exit(2);
  }
  for (final entity in libDir.listSync(recursive: true)) {
    if (entity is! File) continue;
    final normalized = entity.path.replaceAll('\\', '/');
    final fileName = normalized.split('/').last;
    final isTabletSurface =
        normalized.contains('/tablet/') || fileName.contains('tablet');
    if (!isTabletSurface || !normalized.endsWith('.dart')) continue;

    final lines = entity.readAsLinesSync();
    for (var i = 0; i < lines.length; i++) {
      final line = lines[i];
      if (line.trimLeft().startsWith('//')) continue;
      final rel = normalized.replaceFirst('lib/', '');
      if (_literalGapRe.hasMatch(line)) {
        rows.add(SpacingRow(rel, i + 1, 'S1-literal-gap', line.trim()));
      }
      if (_literalInsetRe.hasMatch(line)) {
        rows.add(SpacingRow(rel, i + 1, 'S2-literal-inset', line.trim()));
      }
      if (_literalStrokeRe.hasMatch(line) ||
          (line.contains('Divider(') &&
              RegExp(r'height:\s*\d').hasMatch(line))) {
        rows.add(SpacingRow(rel, i + 1, 'S3-literal-stroke', line.trim()));
      }
    }
  }

  rows.sort((a, b) {
    final byPath = a.path.compareTo(b.path);
    if (byPath != 0) return byPath;
    return a.line.compareTo(b.line);
  });

  final artifact = _renderArtifact(rows);
  if (checkOnly) {
    final existing = File(_artifactPath).existsSync()
        ? File(_artifactPath).readAsStringSync()
        : null;
    if (existing == null || existing != artifact) {
      stderr.writeln(
        'Tablet spacing audit artifact is stale. '
        'Run `dart run tool/tablet_spacing_audit.dart` from flutter_app/.',
      );
      exit(1);
    }
    stdout.writeln('Tablet spacing audit artifact is current.');
  } else {
    File(_artifactPath).writeAsStringSync(artifact);
    stdout.writeln('Wrote $_artifactPath');
  }

  stdout.writeln(
    rows.isEmpty
        ? 'Tablet spacing audit: 0 violations (absolute lock — no baseline).'
        : 'Tablet spacing audit: ${rows.length} violations (absolute lock — '
              'fix by moving to AppSpacing/module tokens, never baseline them).',
  );
}

String _renderArtifact(List<SpacingRow> rows) {
  final buffer = StringBuffer()
    ..writeln('path,line,rule,source')
    ..writeln(
      '# Generated by tool/tablet_spacing_audit.dart — regenerate after touching tablet presentation files.',
    );
  for (final row in rows) {
    buffer.writeln(
      '${row.path},${row.line},${row.rule},"${row.source.replaceAll('"', '""')}"',
    );
  }
  return buffer.toString();
}

class SpacingRow {
  const SpacingRow(this.path, this.line, this.rule, this.source);

  final String path;
  final int line;
  final String rule;
  final String source;
}
