// Tablet Card & Border Standard — audit scanner.
//
// Enforces the static half of
// docs/02_FLUTTER_MIGRATION/standards/Tablet-Card-Border-Standard.md across
// every tablet-surface Dart file under lib/ (path contains "/tablet/" or the
// file name mentions "tablet"):
//
//   R1 raw-border    — no hand-rolled `Border.all(`/`BorderSide(` in tablet
//                      presentation code; frames come from VitCard only.
//   R2 ad-hoc tint   — a `borderColor:` override tinted via
//                      `.withValues(alpha: X)` must use one of the three
//                      sanctioned tint steps {.12, .22, .34}; plain color
//                      tokens (incl. AppColors.transparent) pass untouched.
//   R3 literal radius— `BorderRadius.circular(`/`Radius.circular(` are
//                      forbidden outright (0 tolerance; the whole lib/ is
//                      already at zero — keep it there).
//
// Usage (from flutter_app/):
//   dart run tool/tablet_card_border_audit.dart              # regen artifact
//   dart run tool/tablet_card_border_audit.dart --check      # CI staleness
//   dart run tool/tablet_card_border_audit.dart --regen-baseline
import 'dart:io';

const _artifactPath =
    '../docs/02_FLUTTER_MIGRATION/audits/VitTrade-Tablet-Card-Border-Audit.csv';
const _baselinePath = 'test/quality/tablet_card_border_baseline.txt';

/// Sanctioned tint steps from the standard (subtle / standard / strong).
const _sanctionedTints = <String>{'.12', '.22', '.34', '0.12', '0.22', '0.34'};

final _rawBorderRe = RegExp(r'Border\.all\(|\bBorderSide\s*\(');
final _borderColorTintRe = RegExp(
  r'borderColor:\s*[^\n]+?\.withValues\(\s*alpha:\s*(\d*\.?\d+)\s*\)',
);
final _literalRadiusRe = RegExp(
  r'BorderRadius\.circular\(|\bRadius\.circular\(',
);

void main(List<String> args) {
  final checkOnly = args.contains('--check');
  final regenBaseline = args.contains('--regen-baseline');

  final rows = <BorderRow>[];
  final libDir = Directory('lib');
  if (!libDir.existsSync()) {
    stderr.writeln('Run from flutter_app/ — lib/ not found.');
    exit(2);
  }
  for (final entity in libDir.listSync(recursive: true)) {
    if (entity is! File) continue;
    final normalized = entity.path.replaceAll('\\', '/');
    final fileName = normalized.split('/').last;
    final isTabletSurface =
        normalized.contains('/tablet/') || fileName.contains('tablet');
    if (!isTabletSurface || !normalized.endsWith('.dart')) continue;

    final lines = entity.readAsLinesSync();
    for (var i = 0; i < lines.length; i++) {
      final line = lines[i];
      if (line.trimLeft().startsWith('//')) continue;
      final rel = normalized.replaceFirst('lib/', '');
      if (_rawBorderRe.hasMatch(line)) {
        rows.add(BorderRow(rel, i + 1, 'R1-raw-border', line.trim()));
        continue;
      }
      final tint = _borderColorTintRe.firstMatch(line);
      if (tint != null) {
        if (!_sanctionedTints.contains(tint.group(1)!.trimLeft())) {
          rows.add(
            BorderRow(
              rel,
              i + 1,
              'R2-adhoc-tint(${tint.group(1)})',
              line.trim(),
            ),
          );
        }
        continue;
      }
      if (_literalRadiusRe.hasMatch(line)) {
        rows.add(BorderRow(rel, i + 1, 'R3-literal-radius', line.trim()));
      }
    }
  }

  rows.sort((a, b) {
    final byPath = a.path.compareTo(b.path);
    if (byPath != 0) return byPath;
    return a.line.compareTo(b.line);
  });

  final artifact = _renderArtifact(rows);
  if (regenBaseline) {
    File(_baselinePath).writeAsStringSync(_renderBaseline(rows));
    stdout.writeln('Wrote $_baselinePath (${rows.length} entries).');
  }
  if (checkOnly) {
    final existing = File(_artifactPath).existsSync()
        ? File(_artifactPath).readAsStringSync()
        : null;
    if (existing == null || existing != artifact) {
      stderr.writeln(
        'Tablet card border audit artifact is stale. '
        'Run `dart run tool/tablet_card_border_audit.dart` from flutter_app/.',
      );
      exit(1);
    }
    stdout.writeln('Tablet card border audit artifact is current.');
  } else {
    File(_artifactPath).writeAsStringSync(artifact);
    stdout.writeln('Wrote $_artifactPath');
  }

  final byRule = <String, int>{};
  for (final row in rows) {
    final key = row.rule.split('(').first;
    byRule[key] = (byRule[key] ?? 0) + 1;
  }
  stdout.writeln(
    'Tablet card border audit: ${byRule.isEmpty ? "0 violations" : byRule.entries.map((e) => "${e.value} ${e.key}").join(", ")} '
    '(ratchet down via test/quality/tablet_card_border_baseline.txt).',
  );
}

String _renderArtifact(List<BorderRow> rows) {
  final buffer = StringBuffer()
    ..writeln('path,line,rule,source')
    ..writeln(
      '# Generated by tool/tablet_card_border_audit.dart — regenerate after touching tablet presentation files.',
    );
  for (final row in rows) {
    buffer.writeln(
      '${row.path},${row.line},${row.rule},"${row.source.replaceAll('"', '""')}"',
    );
  }
  return buffer.toString();
}

String _renderBaseline(List<BorderRow> rows) {
  final buffer = StringBuffer()
    ..writeln(
      '# Tablet card border debt baseline — ratchet: entries may only be REMOVED.',
    )
    ..writeln('# Regenerate intentionally via:')
    ..writeln(
      '#   dart run tool/tablet_card_border_audit.dart --regen-baseline',
    )
    ..writeln(
      '# Never add entries by hand; new tablet UI must follow the standard outright.',
    );
  for (final row in rows) {
    buffer.writeln('${row.path}|${row.line}|${row.rule}');
  }
  return buffer.toString();
}

class BorderRow {
  const BorderRow(this.path, this.line, this.rule, this.source);

  final String path;
  final int line;
  final String rule;
  final String source;
}
